#!/bin/bash
# convert_sprites.sh
# Converts all .BMP files under sprites/ into src/sprites.h
# Run from the project root: ./convert_sprites.sh
#
# Expected filename format:  <SIZE>_<STATE>_<N>.bmp
#   SIZE:  SMALL | MEDIUM | LARGE
#   STATE: IDLE | TRANSFER | CONNECT | ENDTRANSFER
#   N:     frame number (1, 2, 3 ...)
#
# Example: sprites/hangyodon/SMALL_IDLE_1.bmp

set -e

SPRITES_DIR="sprites"
OUTPUT="src/sprites.h"

if [ ! -d "$SPRITES_DIR" ]; then
    echo "Error: '$SPRITES_DIR' directory not found. Run from project root."
    exit 1
fi

echo "Generating $OUTPUT..."

cat > "$OUTPUT" << 'HEADER'
#pragma once
#include <stdint.h>

// Auto-generated by convert_sprites.sh — do not edit manually.
// Re-run ./convert_sprites.sh from the project root to regenerate.

HEADER

BMPS=$(find "$SPRITES_DIR" -iname "*.bmp" | sort)
if [ -z "$BMPS" ]; then
    echo "Error: No .BMP files found under $SPRITES_DIR/"
    exit 1
fi

STRUCT_ENTRIES=""
COUNT=0

for BMP in $BMPS; do
    REL="${BMP#$SPRITES_DIR/}"
    CHARACTER=$(echo "$REL" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
    BASENAME=$(basename "$BMP" | tr '[:lower:]' '[:upper:]' | sed 's/\.BMP$//')

    # Parse SIZE_STATE_N  (e.g. SMALL_IDLE_1)
    TIER_STR=$(echo "$BASENAME" | cut -d'_' -f1)
    STATE_STR=$(echo "$BASENAME" | cut -d'_' -f2)

    case "$TIER_STR" in
        SMALL)  TIER="TIER_SMALL"  ;;
        MEDIUM) TIER="TIER_MEDIUM" ;;
        LARGE)  TIER="TIER_LARGE"  ;;
        *)
            echo "  Warning: unknown size '$TIER_STR' in $BMP — skipping"
            continue
            ;;
    esac

    case "$STATE_STR" in
        IDLE)         STATE="STATE_IDLE"         ;;
        TRANSFER)     STATE="STATE_TRANSFER"     ;;
        CONNECT)      STATE="STATE_CONNECT"      ;;
        ENDTRANSFER)  STATE="STATE_ENDTRANSFER"  ;;
        *)
            echo "  Warning: unknown state '$STATE_STR' in $BMP — skipping"
            continue
            ;;
    esac

    # C symbol: sprite_hangyodon_small_idle_1
    SYMBOL="sprite_$(echo "${CHARACTER}_${BASENAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')"

    SIZE=$(wc -c < "$BMP")
    echo "  $BMP -> $SYMBOL ($SIZE bytes, $TIER, $STATE)"

    echo "// $BMP" >> "$OUTPUT"
    echo "static const uint8_t ${SYMBOL}[] = {" >> "$OUTPUT"
    xxd -i < "$BMP" | sed 's/^/    /' >> "$OUTPUT"
    echo "};" >> "$OUTPUT"
    echo "static const uint32_t ${SYMBOL}_len = $SIZE;" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    STRUCT_ENTRIES="${STRUCT_ENTRIES}    { ${SYMBOL}, ${SYMBOL}_len, ${TIER}, ${STATE}, \"${CHARACTER}\" },\n"
    COUNT=$((COUNT + 1))
done

cat >> "$OUTPUT" << FOOTER

// ── Sprite table ──────────────────────────────────────────────────────────────
// Tier and AnimState values match the enums in main.c.

typedef struct {
    const uint8_t *data;
    uint32_t       len;
    int            tier;       // Tier enum
    int            state;      // AnimState enum
    const char    *character;
} SpriteEntry;

static const SpriteEntry sprite_table[] = {
$(printf "$STRUCT_ENTRIES")};

static const int sprite_table_len = $COUNT;
FOOTER

echo "Done — $COUNT sprite(s) written to $OUTPUT"